config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'portfolio', to: 'pages#portfolio', as: :portfolio
  get 'travel', to: 'pages#travel', as: :travel
  get 'gifter', to: 'pages#gifter', as: :gifter
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def portfolio
  end

  def travel
  end

  def gifter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mywebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-container">
  <h1>ABOUT</h1>
  <!-- <div class="about-photo">
    <%= cl_image_tag("prof", width: 300, length: 220) %>
  </div> -->
  <div class="about-flex">
    <div class="about-description">
      <p>
        Passionate about learning
      </p>
    </div>
    <div class="about-resume">
      <div class="about-education">
        <h4>EDUCATION</h4>
        <p><strong>University of Southern California, Marshall School of Business</strong><br>
        Bachelor of Science in Business Administration, Emphasis in Cinematic Arts
        </p>
        <p><strong>Le Wagon</strong><br>
        Full-Stack Coding Certification</p>
        <p><strong>Springboard</strong><br>
        UX/UI Design Certification</p>
      </div>
      <!-- <div class="about-work">
        <h4>EXPERIENCE</h4>
        <p><strong>IMAX Corporation</strong><br>
        <i>Marvel’s Inhumans Theatrical Experience Intern</i><br>
        • Collaborated with four interns to design and produce animated brand campaign advertisement and presented to CEO and company, resulting in private meeting with executives.
        <br>
        • Built comprehensive excel spreadsheet to evaluate data from 10 different departments in order to facilitate distribution of television show and efficiently meet multiple deadlines.
        <br>
        • Coordinated the planning and distribution of promotional assets with over 100 theaters worldwide.
        </p>
      </div> -->
      <div class="about-skills">
        <h4>SKILLS</h4>
      </div>
    </div>
  </div>

  <div class="nav">
    <%= link_to "ABOUT", about_path, {:style=>'font-weight:700;'} %>
    <%= link_to "PORTFOLIO", portfolio_path %>
    <%= link_to "CONTACT", contact_path %>
    <%= link_to "TRAVEL", travel_path %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-container">
  <h1>CONTACT</h1>
  <h6>Please feel free to reach out and chat!</h6>


  <div class="nav">
    <%= link_to "ABOUT", about_path %>
    <%= link_to "PORTFOLIO", portfolio_path %>
    <%= link_to "CONTACT", contact_path, {:style=>'font-weight:700;'}%>
    <%= link_to "TRAVEL", travel_path %>
  </div>
</div>

app/views/pages/gifter.html.erb
<div class="gifter-container">
  <h1>GIFTER</h1>
  <div class="gifter-information">
    <div class="gifter-introduction">
      <h4>Introduction</h4>
      <p>During my two final weeks at Le Wagon, a 9-week intensive coding bootcamp, my team and I designed, implemented and shipped to production a Rails project. Gifter is a crowdfunding platform for gifts for kids.</p>
    </div>
    <div class="gifter-gallery">
      <h4>Wireframing</h4>
      <%= cl_image_tag("front_page", width: 300, length: 300) %>
      <%= cl_image_tag("sign_up", width: 300, length: 300) %>
      <%= cl_image_tag("sign_up_2", width: 300, length: 300) %>
      <%= cl_image_tag("event_dashboard", width: 300, length: 300) %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">
   <div class="currently">
    <p>Currently: 22.3964° N, 114.1095° E</p>
  </div>

  <div class="home-title">
    <h1>黃銘儀 ALISA MING YI NG</h1>
    <p>UX/UI Designer, Full-Stack Web Developer, Undiscovered Artist Enthusiast</p>
  </div>

  <div class="nav">
    <%= link_to "ABOUT", about_path %>
    <%= link_to "PORTFOLIO", portfolio_path %>
    <%= link_to "CONTACT", contact_path %>
    <%= link_to "TRAVEL", travel_path %>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div class="portfolio-container">
  <div class="ohsnap">
  </div>

  <div class="gifter">
    1. <%= link_to "GIFTER", gifter_path %>
  </div>

  <div class="nav">
    <%= link_to "ABOUT", about_path %>
    <%= link_to "PORTFOLIO", portfolio_path, {:style=>'font-weight:700;'} %>
    <%= link_to "CONTACT", contact_path %>
    <%= link_to "TRAVEL", travel_path %>
  </div>
</div>

app/views/pages/travel.html.erb
<!-- <div class="travel-container">
  <h1>TRAVEL</h1>

  <div class="travel-post">
    <div class="travel-photo-1">
      <%= cl_image_tag("vsco5ac697d978d7a", width: 200, length: 200) %>
    </div> -->
  <!--   <div class="travel-photo-2">
      <%= cl_image_tag("vsco5ac267e06b433", width: 120, length: 200) %>
    </div>
     <div class="travel-photo-3">
      <%= cl_image_tag("vsco5ac12ee5f20e6", width: 120, length: 100) %>
    </div> -->
    <!-- <div class="travel-location">
      <h4>CROATIA</h4>
    </div>
  </div>

  <div class="nav">
    <%= link_to "ABOUT", about_path %>
    <%= link_to "PORTFOLIO", portfolio_path %>
    <%= link_to "CONTACT", contact_path %>
    <%= link_to "TRAVEL", travel_path, {:style=>'font-weight:700;'} %>
  </div>
</div>
 -->